add<id=8>= '\+'
sub<id=9>= '\-'
mul<id=14>= '\*'
div<id=15>= '/'
lparen<id=12>= '\('
rparen<id=13>= '\)'
integer<id=11>= '[0-9]+'
identifier<id=10>= '[A-Z_a-z][0-9A-Z_a-z]*'
whitespace<id=16, hidden>= '\s+'

