//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParsleyDemo {
    using System.Collections.Generic;
    
    internal class JsonTokenizer : TableTokenizer {
        internal static DfaEntry[] DfaTable = new DfaEntry[] {
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        '-',
                                        '-'}, 1),
                            new DfaTransitionEntry(new char[] {
                                        '0',
                                        '0'}, 2),
                            new DfaTransitionEntry(new char[] {
                                        '1',
                                        '9'}, 8),
                            new DfaTransitionEntry(new char[] {
                                        '\"',
                                        '\"'}, 9),
                            new DfaTransitionEntry(new char[] {
                                        't',
                                        't'}, 19),
                            new DfaTransitionEntry(new char[] {
                                        'f',
                                        'f'}, 23),
                            new DfaTransitionEntry(new char[] {
                                        'n',
                                        'n'}, 28),
                            new DfaTransitionEntry(new char[] {
                                        '[',
                                        '['}, 32),
                            new DfaTransitionEntry(new char[] {
                                        ']',
                                        ']'}, 33),
                            new DfaTransitionEntry(new char[] {
                                        '{',
                                        '{'}, 34),
                            new DfaTransitionEntry(new char[] {
                                        '}',
                                        '}'}, 35),
                            new DfaTransitionEntry(new char[] {
                                        ':',
                                        ':'}, 36),
                            new DfaTransitionEntry(new char[] {
                                        ',',
                                        ','}, 37),
                            new DfaTransitionEntry(new char[] {
                                        '\t',
                                        '\n',
                                        '\r',
                                        '\r',
                                        ' ',
                                        ' '}, 38)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        '0',
                                        '0'}, 2),
                            new DfaTransitionEntry(new char[] {
                                        '1',
                                        '9'}, 8)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        '.',
                                        '.'}, 3),
                            new DfaTransitionEntry(new char[] {
                                        '0',
                                        '9'}, 4),
                            new DfaTransitionEntry(new char[] {
                                        'E',
                                        'E',
                                        'e',
                                        'e'}, 5)}, 16),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        '0',
                                        '9'}, 4)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        '0',
                                        '9'}, 4),
                            new DfaTransitionEntry(new char[] {
                                        'E',
                                        'E',
                                        'e',
                                        'e'}, 5)}, 16),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        '+',
                                        '+',
                                        '-',
                                        '-'}, 6),
                            new DfaTransitionEntry(new char[] {
                                        '0',
                                        '9'}, 7)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        '0',
                                        '9'}, 7)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        '0',
                                        '9'}, 7)}, 16),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        '0',
                                        '9'}, 8),
                            new DfaTransitionEntry(new char[] {
                                        '.',
                                        '.'}, 3),
                            new DfaTransitionEntry(new char[] {
                                        'E',
                                        'E',
                                        'e',
                                        'e'}, 5)}, 16),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        '\0',
                                        '\t',
                                        '',
                                        '!',
                                        '#',
                                        '[',
                                        ']',
                                        '￿'}, 9),
                            new DfaTransitionEntry(new char[] {
                                        '\\',
                                        '\\'}, 10),
                            new DfaTransitionEntry(new char[] {
                                        '\"',
                                        '\"'}, 18)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        '\"',
                                        '\"',
                                        '/',
                                        '/',
                                        '\\',
                                        '\\',
                                        'b',
                                        'b',
                                        'f',
                                        'f',
                                        'n',
                                        'n',
                                        'r',
                                        'r',
                                        't',
                                        't'}, 9),
                            new DfaTransitionEntry(new char[] {
                                        'u',
                                        'u'}, 11)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        'A',
                                        'F',
                                        'a',
                                        'f'}, 12)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        'A',
                                        'F',
                                        'a',
                                        'f'}, 13)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        'A',
                                        'F',
                                        'a',
                                        'f'}, 14)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        'A',
                                        'F',
                                        'a',
                                        'f'}, 15)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        'A',
                                        'F',
                                        'a',
                                        'f'}, 16)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        'A',
                                        'F',
                                        'a',
                                        'f'}, 17)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        'A',
                                        'F',
                                        'a',
                                        'f'}, 9)}, -1),
                new DfaEntry(new DfaTransitionEntry[0], 12),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        'r',
                                        'r'}, 20)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        'u',
                                        'u'}, 21)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        'e',
                                        'e'}, 22)}, -1),
                new DfaEntry(new DfaTransitionEntry[0], 18),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        'a',
                                        'a'}, 24)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        'l',
                                        'l'}, 25)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        's',
                                        's'}, 26)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        'e',
                                        'e'}, 27)}, -1),
                new DfaEntry(new DfaTransitionEntry[0], 19),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        'u',
                                        'u'}, 29)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        'l',
                                        'l'}, 30)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        'l',
                                        'l'}, 31)}, -1),
                new DfaEntry(new DfaTransitionEntry[0], 17),
                new DfaEntry(new DfaTransitionEntry[0], 14),
                new DfaEntry(new DfaTransitionEntry[0], 15),
                new DfaEntry(new DfaTransitionEntry[0], 10),
                new DfaEntry(new DfaTransitionEntry[0], 11),
                new DfaEntry(new DfaTransitionEntry[0], 13),
                new DfaEntry(new DfaTransitionEntry[0], 20),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        '\t',
                                        '\n',
                                        '\r',
                                        '\r',
                                        ' ',
                                        ' '}, 38)}, 21)};
        internal static int[] NodeFlags = new int[] {
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1};
        internal static string[] BlockEnds = new string[] {
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null};
        public JsonTokenizer(IEnumerable<char> input) : 
                base(JsonTokenizer.DfaTable, JsonTokenizer.BlockEnds, JsonTokenizer.NodeFlags, input) {
        }
        public const int lbrace = 10;
        public const int rbrace = 11;
        public const int @string = 12;
        public const int colon = 13;
        public const int lbracket = 14;
        public const int rbracket = 15;
        public const int number = 16;
        public const int @null = 17;
        public const int @true = 18;
        public const int @false = 19;
        public const int comma = 20;
        public const int whitespace = 21;
    }
}
