//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParsleyDemo {
    using System.Collections.Generic;
    
    internal class JsonTokenizer : TableTokenizer {
        internal static DfaEntry[] DfaTable = new DfaEntry[] {
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        '\t',
                                        '\n',
                                        '\r',
                                        '\r',
                                        ' ',
                                        ' '}, 1),
                            new DfaTransitionEntry(new char[] {
                                        ',',
                                        ','}, 2),
                            new DfaTransitionEntry(new char[] {
                                        ':',
                                        ':'}, 3),
                            new DfaTransitionEntry(new char[] {
                                        '}',
                                        '}'}, 4),
                            new DfaTransitionEntry(new char[] {
                                        '{',
                                        '{'}, 5),
                            new DfaTransitionEntry(new char[] {
                                        ']',
                                        ']'}, 6),
                            new DfaTransitionEntry(new char[] {
                                        '[',
                                        '['}, 7),
                            new DfaTransitionEntry(new char[] {
                                        'n',
                                        'n'}, 8),
                            new DfaTransitionEntry(new char[] {
                                        'f',
                                        'f'}, 12),
                            new DfaTransitionEntry(new char[] {
                                        't',
                                        't'}, 17),
                            new DfaTransitionEntry(new char[] {
                                        '\"',
                                        '\"'}, 21),
                            new DfaTransitionEntry(new char[] {
                                        '-',
                                        '-'}, 31),
                            new DfaTransitionEntry(new char[] {
                                        '0',
                                        '0'}, 32),
                            new DfaTransitionEntry(new char[] {
                                        '1',
                                        '9'}, 38)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        '\t',
                                        '\n',
                                        '\r',
                                        '\r',
                                        ' ',
                                        ' '}, 1)}, 25),
                new DfaEntry(new DfaTransitionEntry[0], 24),
                new DfaEntry(new DfaTransitionEntry[0], 23),
                new DfaEntry(new DfaTransitionEntry[0], 22),
                new DfaEntry(new DfaTransitionEntry[0], 21),
                new DfaEntry(new DfaTransitionEntry[0], 20),
                new DfaEntry(new DfaTransitionEntry[0], 19),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        'u',
                                        'u'}, 9)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        'l',
                                        'l'}, 10)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        'l',
                                        'l'}, 11)}, -1),
                new DfaEntry(new DfaTransitionEntry[0], 18),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        'a',
                                        'a'}, 13)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        'l',
                                        'l'}, 14)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        's',
                                        's'}, 15)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        'e',
                                        'e'}, 16)}, -1),
                new DfaEntry(new DfaTransitionEntry[0], 17),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        'r',
                                        'r'}, 18)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        'u',
                                        'u'}, 19)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        'e',
                                        'e'}, 20)}, -1),
                new DfaEntry(new DfaTransitionEntry[0], 16),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        '\0',
                                        '\t',
                                        '',
                                        '!',
                                        '#',
                                        '[',
                                        ']',
                                        '￿'}, 21),
                            new DfaTransitionEntry(new char[] {
                                        '\\',
                                        '\\'}, 22),
                            new DfaTransitionEntry(new char[] {
                                        '\"',
                                        '\"'}, 30)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        '\"',
                                        '\"',
                                        '/',
                                        '/',
                                        '\\',
                                        '\\',
                                        'b',
                                        'b',
                                        'f',
                                        'f',
                                        'n',
                                        'n',
                                        'r',
                                        'r',
                                        't',
                                        't'}, 21),
                            new DfaTransitionEntry(new char[] {
                                        'u',
                                        'u'}, 23)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        'A',
                                        'F',
                                        'a',
                                        'f'}, 24)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        'A',
                                        'F',
                                        'a',
                                        'f'}, 25)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        'A',
                                        'F',
                                        'a',
                                        'f'}, 26)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        'A',
                                        'F',
                                        'a',
                                        'f'}, 27)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        'A',
                                        'F',
                                        'a',
                                        'f'}, 28)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        'A',
                                        'F',
                                        'a',
                                        'f'}, 29)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        'A',
                                        'F',
                                        'a',
                                        'f'}, 21)}, -1),
                new DfaEntry(new DfaTransitionEntry[0], 15),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        '0',
                                        '0'}, 32),
                            new DfaTransitionEntry(new char[] {
                                        '1',
                                        '9'}, 38)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        '.',
                                        '.'}, 33),
                            new DfaTransitionEntry(new char[] {
                                        '0',
                                        '9'}, 34),
                            new DfaTransitionEntry(new char[] {
                                        'E',
                                        'E',
                                        'e',
                                        'e'}, 35)}, 14),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        '0',
                                        '9'}, 34)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        '0',
                                        '9'}, 34),
                            new DfaTransitionEntry(new char[] {
                                        'E',
                                        'E',
                                        'e',
                                        'e'}, 35)}, 14),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        '+',
                                        '+',
                                        '-',
                                        '-'}, 36),
                            new DfaTransitionEntry(new char[] {
                                        '0',
                                        '9'}, 37)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        '0',
                                        '9'}, 37)}, -1),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        '0',
                                        '9'}, 37)}, 14),
                new DfaEntry(new DfaTransitionEntry[] {
                            new DfaTransitionEntry(new char[] {
                                        '0',
                                        '9'}, 38),
                            new DfaTransitionEntry(new char[] {
                                        '.',
                                        '.'}, 33),
                            new DfaTransitionEntry(new char[] {
                                        'E',
                                        'E',
                                        'e',
                                        'e'}, 35)}, 14)};
        internal static int[] NodeFlags = new int[] {
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1};
        internal static string[] BlockEnds = new string[] {
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null};
        public JsonTokenizer(IEnumerable<char> input) : 
                base(JsonTokenizer.DfaTable, JsonTokenizer.BlockEnds, JsonTokenizer.NodeFlags, input) {
        }
        public const int number = 14;
        public const int @string = 15;
        public const int @true = 16;
        public const int @false = 17;
        public const int @null = 18;
        public const int lbracket = 19;
        public const int rbracket = 20;
        public const int lbrace = 21;
        public const int rbrace = 22;
        public const int colon = 23;
        public const int comma = 24;
        public const int whitespace = 25;
    }
}
