number<id=16>= '\-?(0|[1-9][0-9]*)(\.[0-9]+)?([Ee][\+\-]?[0-9]+)?'
string<id=14>= '"([^\n"\\]|\\([btrnf"\\/]|(u[A-Fa-f]{4})))*"'
true<id=18>= 'true'
false<id=19>= 'false'
null<id=17>= 'null'
lbracket<id=24, collapsed>= '\['
rbracket<id=22, collapsed>= '\]'
lbrace<id=23, collapsed>= '\{'
rbrace<id=21, collapsed>= '\}'
colon<id=15, collapsed>= ':'
comma<id=20, collapsed>= ','
whitespace<id=25, hidden>= '[ \t\r\n\f\v]+'

