whitespace<id=25, hidden>= '[\n\r\t ]+'
comma<id=24, collapsed>= ','
colon<id=23, collapsed>= ':'
rbrace<id=22, collapsed>= '\}'
lbrace<id=21, collapsed>= '\{'
rbracket<id=20, collapsed>= '\]'
lbracket<id=19, collapsed>= '\['
null<id=18, terminal>= 'null'
false<id=17, terminal>= 'false'
true<id=16, terminal>= 'true'
string<id=15, terminal>= '"([^\n"\\]|\\([btrnf"\\/]|(u[A-Fa-f]{4})))*"'
number<id=14, terminal>= '\-?(0|[1-9][0-9]*)(\.[0-9]+)?([Ee][\+\-]?[0-9]+)?'

