integer<id=7>= '[0-9]+'
identifier<id=8>= '[A-Z_a-z][0-9A-Z_a-z]*'
whitespace<id=11, hidden>= '\s+'
add<id=10>= '\+'
sub<id=-1>= '\-'
mul<id=9>= '\*'
div<id=-1>= '/'
lparen<id=5>= '\('
rparen<id=6>= '\)'

