add<id=12>= '\+'
mul<id=18>= '\*'
integer<id=14>= '[0-9]+'
identifier<id=15>= '[A-Z_a-z][0-9A-Z_a-z]*'
whitespace<id=20, hidden>= '[ \t\r\n]+'
lineComment<id=21, hidden, blockEnd= "\n">= '//'
blockComment<id=22, hidden, blockEnd= "*/">= '/\*'
Implicit<id=13>= '\-'
Implicit2<id=19>= '/'
Implicit3<id=16>= '\('
Implicit4<id=17>= '\)'

