add<id=12, terminal>= '\+'
mul<id=18, terminal>= '\*'
integer<id=14, terminal>= '[0-9]+'
identifier<id=15, terminal>= '[A-Z_a-z][0-9A-Z_a-z]*'
whitespace<id=20, hidden>= '\s+'
Implicit<id=13>= '\-'
Implicit2<id=19>= '/'
Implicit3<id=16>= '\('
Implicit4<id=17>= '\)'

