number<id=18>= '\-?(0|[1-9][0-9]*)(\.[0-9]+)?([Ee][\+\-]?[0-9]+)?'
string<id=16>= '"([^"\\]|\\.)*"'
true<id=20>= 'true'
false<id=21>= 'false'
null<id=19>= 'null'
lbracket<id=25, collapsed>= '\['
rbracket<id=26, collapsed>= '\]'
lbrace<id=23, collapsed>= '\{'
rbrace<id=24, collapsed>= '\}'
colon<id=17, collapsed>= ':'
comma<id=22, collapsed>= ','
whitespace<id=27, hidden>= '[ \t\r\n\f\v]+'

