number<id=16, terminal>= '\-?(0|[1-9][0-9]*)(\.[0-9]+)?([Ee][\+\-]?[0-9]+)?'
string<id=14, terminal>= '"([^\n"\\]|\\([btrnf"\\/]|(u[A-Fa-f]{4})))*"'
true<id=18, terminal>= 'true'
false<id=19, terminal>= 'false'
null<id=17, terminal>= 'null'
lbracket<id=24, collapsed>= '\['
rbracket<id=22, collapsed>= '\]'
lbrace<id=23, collapsed>= '\{'
rbrace<id=21, collapsed>= '\}'
colon<id=15, collapsed>= ':'
comma<id=20, collapsed>= ','
whitespace<id=25, hidden>= '[\n\r\t ]+'

